### ISSUE TITLE
Type mismatch error when getting verification

### ISSUE THREAD

**Issue by Takayuki-Suzuki** [Psychedelic/cover-sdk#29]
Hi, I'm trying to fetch verification info.

```js
const verification = await cover.getVerificationByCanisterId(Principal.fromText("lj532-6iaaa-aaaah-qcc7a-cai"));
```

But this fails with :
```
Uncaught Error: type mismatch: type on the wire rec_23, expect type text
    at TextClass.checkType (/node_modules/@dfinity/candid/lib/cjs/idl.js:152:19)
    at TextClass.decodeValue (/node_modules/@dfinity/candid/lib/cjs/idl.js:371:14)
    at RecordClass.decodeValue (/node_modules/@dfinity/candid/lib/cjs/idl.js:839:39)
    at OptClass.decodeValue (/node_modules/@dfinity/candid/lib/cjs/idl.js:743:36)
```

SDK version is 0.0.17.

**Comment by scott-dn** [comment]
it should be fixed now, thanks for reporting.
